export const base = [
  {
    nome: "Naruto Uzumaki",
    universo: "Naruto",
    tipo: "herói",
    cla: "Uzumaki",
    raca: null,
    poder: 9500,
    habilidades: ["Rasengan", "Modo Sabio", "Kurama"],
  },
  {
    nome: "Sasuke Uchiha",
    universo: "Naruto",
    tipo: "herói",
    cla: "Uchiha",
    raca: null,
    poder: 9400,
    habilidades: ["Chidori", "Sharingan", "Rinnegan"],
  },
  {
    nome: "Orochimaru",
    universo: "Naruto",
    tipo: "vilao",
    cla: null,
    raca: null,
    poder: 8900,
    habilidades: ["Invocacao de cobras", "Imortalidade"],
  },
  {
    nome: "Madara Uchiha",
    universo: "Naruto",
    tipo: "vilao",
    cla: "Uchiha",
    raca: null,
    poder: 9900,
    habilidades: ["Susanoo", "Rinnegan", "Mokuton"],
  },{
    nome: "itachi Uchiha",
    universo: "Naruto",
    tipo: "herói",
    cla: "Uchiha",
    raca: null,
    poder: 9200,
    habilidades: ["Tsukuyomi", "Amaterasu", "Susanoo"],
  },
  {
    nome: "Goku",
    universo: "Dragon Ball",
    tipo: "herói",
    cla: null,
    raca: "Saiyajin",
    poder: 10000,
    habilidades: ["Super Saiyajin", "Ultra Instinct"],
  },
  {
    nome: "Vegeta",
    universo: "Dragon Ball",
    tipo: "herói",
    cla: null,
    raca: "Saiyajin",
    poder: 9800,
    habilidades: ["Super Saiyajin", "SSJ Blue", "Ego Superior"],
  },
  {
    nome: "Freeza",
    universo: "Dragon Ball",
    tipo: "vilao",
    cla: null,
    raca: "Desconhecida",
    poder: 9600,
    habilidades: ["Forma Final", "Golden Freeza", "Black Freeza"],
  },
  {
    nome: "Cell",
    universo: "Dragon Ball",
    tipo: "vilao",
    cla: null,
    raca: "Bio-Android",
    poder: 9200,
    habilidades: ["Forma Perfeita"],
  },
];
